-- HSK1 (v3.0) Vocabulary Seed Script - STAGING at Level 10
-- Generated: 2025-12-04T14:48:36.290Z
-- Total entries: 505
-- 
-- This seeds vocab at HSK level 10 for side-by-side comparison
-- with existing HSK level 1 vocabulary.
-- 
-- After verification, run:
--   1. Transfer audio/tags from level 1 to matching level 10 words
--   2. UPDATE vocabulary SET hsk_level = 1 WHERE hsk_level = 10;
--   3. DELETE FROM vocabulary WHERE hsk_level = 1 AND id NOT IN (new IDs);

-- STEP 1: Clear any previous level 10 staging data
DELETE FROM vocabulary WHERE hsk_level = 10;

-- STEP 2: Insert new HSK1 (v3.0) vocabulary at staging level 10
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('nM8dMtiiw3Kw', '爱', 'ài', 'love', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('11TuoA5uaFj5', '爱好', 'ài hào', 'hobby', 'general', 10, NULL, '4-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Rw-NzDmNbh3D', '八', 'bā', 'eight', 'numbers', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('x2kF9sNE3geZ', '爸爸', 'bàba', 'dad', 'family', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('VBUX21jX56rg', '爸', 'bà', 'dad', 'family', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('axDO1tYbnGZH', '吧', 'ba', '(interjection particle)', 'general', 10, NULL, '5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('gQuHfW_xsEHS', '白', 'bái', 'white', 'general', 10, 'adjective', '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('PoNeLHjlnDgr', '白天', 'bái tiān', 'day', 'time', 10, NULL, '2-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('9obCIXExYhH4', '百', 'bǎi', 'hundred', 'numbers', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('_7ckOID4Zi3l', '班', 'bān', 'class', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('jtup0fiEBmac', '半', 'bàn', 'half', 'numbers', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('KfAr0P0hsa3I', '半年', 'bàn nián', 'half a year', 'time', 10, NULL, '4-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('vEqjVImQJSCU', '半天', 'bàn tiān', 'half day', 'time', 10, NULL, '4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('XLaGR0_DXtGn', '帮', 'bāng', 'help', 'actions', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('jJEV5w2so8xY', '帮忙', 'bāng máng', 'help', 'actions', 10, NULL, '1-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Bkljg7684qOU', '包', 'bāo', 'package', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('GfahgHDBD4Mn', '包子', 'bāo zi', 'bun', 'food', 10, NULL, '1-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('MjMlENzjYMfY', '杯', 'bēi', 'cup', 'objects', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('eagKCvWEg8nM', '杯子', 'bēi zi', 'cup', 'objects', 10, NULL, '1-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('KtkZLSbqCCLC', '北', 'běi', 'north', 'directions', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('91aUwsodNVaw', '北边', 'běi biān', 'North side', 'directions', 10, NULL, '3-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Q8xHbWjpZhE_', '北京', 'běi jīng', 'Beijing', 'general', 10, NULL, '3-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('-NxeBjcT8d7k', '本', 'běn', '(measure word for books or volumes)', 'general', 10, 'measure', '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('I0l1h-wXqJaN', '本子', 'běn zi', 'book', 'objects', 10, NULL, '3-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('3WWaE0TPRT5G', '比', 'bǐ', 'particle used for comparison', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('JxUZ8R0pjMn0', '别', 'bié', 'Don’t', 'general', 10, 'adverb', '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('w-wRqfIh3yvl', '别的', 'bié de', 'other', 'general', 10, NULL, '2-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('vK43bJWB73Qj', '别人', 'bié·rén', 'other people', 'people', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ezVGLU2qzHgw', '病', 'bìng', 'disease', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('sxJ5CWOGD4wK', '病人', 'bìng rén', 'patient', 'general', 10, NULL, '4-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('jOXq7WWqNLiL', '不大', 'bú dà', 'not big', 'adjectives', 10, NULL, '2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('3PMl_-CJdSbj', '不对', 'bú duì', 'wrong', 'adjectives', 10, NULL, '2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('V2n2FLVLCTIr', '不客气', 'bú kè qì', 'You’re welcome', 'pronouns', 10, NULL, '2-4-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('vgeWoWqmVR1x', '不用', 'bú yòng', 'No need to', 'general', 10, NULL, '2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('mq2-L8kgROXW', '不', 'bù', 'No', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('HdWEfxKnFskl', '菜', 'cài', 'dish', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('zChd8_dTZ0WZ', '茶', 'chá', 'tea', 'food', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('to950aovX3PV', '差', 'chà', 'differ from; bad; short of', 'adjectives', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('niCx-SztiaL-', '常', 'cháng', 'often', 'general', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('VNqfy8aWRRoW', '常常', 'cháng cháng', 'often', 'general', 10, NULL, '2-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('teoNuhaFnXQ3', '唱', 'chàng', 'sing', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('08TS2ZotuaqQ', '唱歌', 'chàng gē', 'sing', 'actions', 10, NULL, '4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('M2RZ9Yel4YyH', '车', 'chē', 'car', 'transportation', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('SKoHxWsAv22G', '车票', 'chē piào', 'ticket', 'transportation', 10, NULL, '1-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('XKeAYfaRPstI', '车上', 'chē shàng', 'in the car', 'transportation', 10, NULL, '1-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('AlV33qgOeH24', '车站', 'chē zhàn', 'station', 'places', 10, NULL, '1-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('cqjih0v9nfda', '吃', 'chī', 'eat', 'food', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('9urTiE4YV5Er', '吃饭', 'chī fàn', 'have meal', 'food', 10, NULL, '1-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('-N0aBuXxejz5', '出', 'chū', 'out', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('kg0KLVZvJ9Mp', '出来', 'chū lái', 'come', 'actions', 10, NULL, '1-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Akwj9LC4b5nm', '出去', 'chū qù', 'go out', 'actions', 10, NULL, '1-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('1HAH1fMK8T7G', '穿', 'chuān', 'wear', 'actions', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('YmH0eGw9KFuZ', '床', 'chuáng', 'bed', 'objects', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('3J6Sumw0Ajb5', '次', 'cì', '(measure word for times, frequency)', 'general', 10, 'measure', '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('3aROVS8i0jP5', '从', 'cóng', 'from', 'general', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('P7-LqYnEPT4-', '错', 'cuò', 'wrong', 'adjectives', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('hluwP4Uh9dZq', '打', 'dǎ', 'hit, take', 'actions', 10, 'verb', '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Ev2JLIT7SkYI', '打车', 'dǎ chē', 'take a taxi', 'transportation', 10, NULL, '3-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('KkUpcZQsj9B7', '打电话', 'dǎ diàn huà', 'make a phonecall', 'actions', 10, NULL, '3-4-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('3vd9BSlNuD1m', '打开', 'dǎ kāi', 'turn on', 'general', 10, NULL, '3-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('KfHOZzDEEEFx', '打球', 'dǎ qiú', 'play ball', 'actions', 10, NULL, '3-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('GjP6R5Ki77lu', '大', 'dà', 'large, big', 'adjectives', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('MZE4tt3L9qAf', '大学', 'dà xué', 'university', 'places', 10, NULL, '4-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('zAtHf3zG_tVv', '大学生', 'dà xué shēng', 'university student', 'places', 10, NULL, '4-2-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('IPnuILB30F_O', '到', 'dào', 'reach', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ZlLm2T5QPsvH', '得到', 'dé dào', 'get', 'general', 10, NULL, '2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('trXdS0KdCDVD', '地', 'de', 'auxiliary word', 'general', 10, NULL, '5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('QeJELcsxfzsD', '的', 'de', '(aux.)', 'general', 10, NULL, '5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('K6blQgjgDql6', '等', 'děng', 'wait', 'actions', 10, 'verb', '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('v2aqEZxZrDJW', '地点', 'dìdiǎn', 'location', 'places', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Q-yFTnHXTY9b', '地方', 'dìfang', 'local', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('jEoTnZyJqlA4', '地上', 'dì shàng', 'on the ground', 'general', 10, NULL, '4-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('6vnw_9g4B7bQ', '地图', 'dìtú', 'Map', 'objects', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('VKqtoeHL2ent', '弟弟', 'dì di', 'younger brother', 'family', 10, NULL, '4-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('E0hLH1K0O0Ny', '弟', 'dì', 'younger brother', 'family', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('lcgq0eYXxry9', '第（第二）', 'dì', 'auxiliary word for ordinal numbers (second )', 'time', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('gy70F6JkJZh0', '点', 'diǎn', 'spot', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('t6NuBwmvQfit', '电', 'diàn', 'electricity', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('__wrOgdG7hXs', '电话', 'diàn huà', 'phone', 'objects', 10, NULL, '4-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('lLTWLrD-cLJi', '电脑', 'diànnǎo', 'Computer', 'objects', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('mQ66SSxugFTJ', '电视', 'diànshì', 'television', 'objects', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('GD5LsxqLRwL1', '电视机', 'diàn shì jī', 'television', 'objects', 10, NULL, '4-4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('VSGc5i4mg-tP', '电影', 'diànyǐng', 'Film', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('XXbxKI2HDTJv', '电影院', 'diàn yǐng yuàn', 'cinema; movie theater', 'places', 10, NULL, '4-3-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('UwqRlao6JmDx', '东', 'dōng', 'east', 'directions', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('mKp0ySbrnzj2', '东边', 'dōng biān', 'east side', 'directions', 10, NULL, '1-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('xUITbyamOYTS', '东西', 'dōngxi', 'thing', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('stF55ZCbkMDC', '动', 'dòng', 'move', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('aC6_F4WRm6wz', '动作', 'dòngzuò', 'action', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('6Sr62lMNh8yn', '都', 'dōu', 'all', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('lh_kfY60dpGX', '读', 'dú', 'read', 'actions', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Cq51Aa9uIP4r', '读书', 'dú shū', 'reading; study', 'actions', 10, NULL, '2-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('NVd9zKenqkdx', '对', 'duì', 'right', 'directions', 10, 'adjective', '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('0f43wbujVTqz', '对不起', 'duìbuqǐ', 'I’m sorry.', 'pronouns', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('TkT8fQBsQjQ4', '多（形、代）', 'duō', 'many; much; more', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('UpyeTC5-q9SF', '多少', 'duōshao', 'how much', 'pronouns', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('J51nBVukveFf', '饿', 'è', 'hungry', 'adjectives', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('kL772Keo_sdi', '儿子', 'érzi', 'Son', 'family', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('DTs1juAjo5OA', '二', 'èr', 'Two', 'numbers', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('W_C2xoqG0daO', '饭', 'fàn', 'rice; meal', 'food', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('pAr3DmkJU7AD', '饭店', 'fàndiàn', 'restaurant', 'food', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('-TOupwjnkaWP', '房间', 'fángjiān', 'Room', 'places', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('m4-VUTYtqZw0', '房子', 'fáng zi', 'house; building', 'places', 10, NULL, '2-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('nLHWuikIAdXa', '放', 'fàng', 'discharge', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('iWaozgHBe3RR', '放假', 'fàng jià', 'holiday; have a holiday', 'general', 10, NULL, '4-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ydslnaFLkuew', '放学', 'fàng xué', 'off school', 'places', 10, NULL, '4-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('dvocmCE-NyXK', '飞', 'fēi', 'fly', 'transportation', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('8R0CkO9txj9D', '飞机', 'fēijī', 'aircraft', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('kR4NeaLyblBW', '非常', 'fēicháng', 'very', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('weQFPwE2Kf7I', '分（名、量）', 'fēn', 'minute; point; part; (measure word)', 'time', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('IaAi2iizN6sp', '风', 'fēng', 'wind', 'weather', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('8gDpDHYgxYzv', '干', 'gān', 'dry', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('9MkbR9M9q-Vf', '干净', 'gānjìng', 'clean', 'adjectives', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('m2rqIDZkzDS5', '干什么', 'gàn shén me', 'What to do', 'actions', 10, NULL, '4-2-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('p-DOcouRzw1l', '高', 'gāo', 'high', 'adjectives', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('3SoaL2oQaw79', '高兴', 'gāoxìng', 'happy', 'adjectives', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('PTrO_QD_AsW-', '告诉', 'gàosu', 'tell', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('3stoa1F_PJsg', '哥哥', 'gē ge', 'elder brother', 'family', 10, NULL, '1-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('_ZZgRK8DRZlP', '哥', 'gē', 'elder brother', 'family', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('-zt6o75CwgVh', '歌', 'gē', 'song', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('GfviNhriW4a_', '个', 'gè', 'individual', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('7B3jZHLzWTcc', '给', 'gěi', 'give', 'actions', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('XQu3fzPQVPRL', '跟', 'gēn', 'with', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('RFGv-XiirhCL', '工人', 'gōngrén', 'Worker', 'people', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('RzfGUhjocZHw', '工作', 'gōngzuò', 'work', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('e64_ObqGwq_0', '关', 'guān', 'shut; close; turn off', 'actions', 10, 'verb', '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('peJVzNxYAjxa', '关上', 'guān shàng', 'close;shut to; turn off', 'actions', 10, NULL, '1-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('qamyyoKg1-WV', '贵', 'guì', 'noble', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('mnSOobXn6Ymh', '国', 'guó', 'country; state; nation', 'general', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('6fsfg9HF5TG0', '国家', 'guójiā', 'Country', 'general', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('tKSBrJ9o0Hrk', '国外', 'guó wài', 'foreign; oversea; abroad', 'general', 10, NULL, '2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('UZCT-3q_XT3y', '过', 'guò', 'pass', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('9OkSt8kA2LSA', '还', 'hái', 'also; still; yet', 'general', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('PSw4rP9QhRo-', '还是', 'háishi', 'still', 'general', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('KcLLPWud4eNS', '还有', 'hái yǒu', 'also; in addition; besides', 'general', 10, NULL, '2-3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('xDK4Tnh9Dka7', '孩子', 'háizi', 'Children', 'family', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('WSHBSOVrJw_6', '汉语', 'hànyǔ', 'Chinese', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('LzXQ3kE5YKCD', '汉字', 'hàn zì', 'Chinese character', 'general', 10, NULL, '4-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('U2--TVB17-Cn', '好', 'hǎo', 'good', 'adjectives', 10, 'adjective', '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('z2m6gcAV1zMA', '好吃', 'hǎochī', 'Yummy', 'food', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('iU9QvDIRuMfa', '好看', 'hǎo kàn', 'good looking', 'adjectives', 10, NULL, '3-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('lkCBMyMIBRcw', '好听', 'hǎo tīng', 'pleasant to hear', 'actions', 10, NULL, '3-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('4tuJv01zrCoV', '好玩儿', 'hǎo wánr', 'fun; interesting', 'adjectives', 10, NULL, '3-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('haFljwBWKH-9', '号', 'hào', 'Number/date', 'time', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('32S-2WwHclCM', '喝', 'hē', 'drink', 'food', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('pWTKRMK0RxA4', '和', 'hé', 'and', 'general', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ElhphXH00IB8', '很', 'hěn', 'very', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('JmiAb5wF-El1', '后', 'hòu', 'back; behind; after; later', 'directions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('5-y7sQJkccmN', '后边', 'hòu biān', 'behind; back', 'directions', 10, NULL, '4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('MAUXPgedLGNZ', '后天', 'hòu tiān', 'day after tomorrow', 'time', 10, NULL, '4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('fmfVhTqn7PjJ', '花', 'huā', 'flower', 'objects', 10, 'noun', '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('9yHdFR9x_u1y', '话', 'huà', 'word; words', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('kRiWYK1_It5e', '坏', 'huài', 'bad', 'adjectives', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('4ymRxMjZ-i2m', '回', 'huí', 'go back; return', 'directions', 10, 'verb', '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('JPrt6g7v200W', '回答', 'huídá', 'Answer', 'actions', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('0rFKJPET9Lpv', '回到', 'huí dào', 'back to', 'directions', 10, NULL, '2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('aAePaFtXS7Qs', '回家', 'huí jiā', 'go home; return home', 'places', 10, NULL, '2-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('HRK10i-wDfEU', '回来', 'huí lái', 'come back; return', 'directions', 10, NULL, '2-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('DgaOTyZQJCYm', '回去', 'huí qù', 'go back', 'directions', 10, NULL, '2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('LbPFHkwZkwRa', '会', 'huì', 'can; be able to', 'general', 10, 'verb', '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('KHWNEGIjqSaK', '火车', 'huǒ chē', 'train', 'transportation', 10, NULL, '3-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Tr3EoIBYvOOQ', '机场', 'jīchǎng', 'Airport', 'places', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('4Y1LgWbGvkBq', '机票', 'jī piào', 'air ticket', 'transportation', 10, NULL, '1-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('f30UKFRwP6vR', '鸡蛋', 'jīdàn', 'Egg', 'food', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('fKL1ZDhWOCpe', '几', 'jǐ', 'several', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Bzxcka8kxabS', '记', 'jì', 'remember', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('TB8hzWdGqh4i', '记得', 'jìdé', 'remember', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('D051zWVlgWlP', '记住', 'jì zhù', 'remember; keep in mind', 'actions', 10, NULL, '4-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('-b_fGXiOnd39', '家', 'jiā', 'home', 'places', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('uDFqwm3CKuVq', '家里', 'jiā lǐ', 'In the home', 'places', 10, NULL, '1-3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('IL-4FKI064DB', '家人', 'jiā rén', 'family', 'family', 10, NULL, '1-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('kDn1uxSEMeWc', '间', 'jiān', 'between; measure word for rooms', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ImDZjHmHix0_', '见', 'jiàn', 'see; meet', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('8OeTdHHRoJJz', '见面', 'jiànmiàn', 'meet', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('iwV601owgrQa', '教', 'jiāo', 'teach', 'actions', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('iYHR2-CkhHhB', '叫', 'jiào', 'call; be called', 'actions', 10, 'verb', '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('3ZhgM-nOTb-C', '教学楼', 'jiào xué lóu', 'teaching building', 'places', 10, NULL, '4-2-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('sDJb-M7qejJg', '姐姐', 'jiě jie', 'elder sister', 'family', 10, NULL, '3-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('M9kJPuRb9YpV', '姐', 'jiě', 'elder sister', 'family', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Wlju5IK1ytwD', '介绍', 'jièshào', 'introduce', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('S_IO62ajleSl', '今年', 'jīn nián', 'this year', 'time', 10, NULL, '1-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('RgflYVfnfRN2', '今天', 'jīntiān', 'Today', 'time', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('i_XUPzSqx8RA', '进', 'jìn', 'enter', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('mzxv9FAD3_O8', '进来', 'jìn lái', 'come in', 'actions', 10, NULL, '4-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('MUr9OqMB2G7p', '进去', 'jìn qù', 'go in', 'actions', 10, NULL, '4-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('4WydQYFjQMs2', '九', 'jiǔ', 'Nine', 'numbers', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('gdSjiFgmwPzN', '就', 'jiù', 'as soon as; right away; then', 'directions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('f7QBy-G1dlnz', '觉得', 'juéde', 'Think', 'actions', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('9GqOb4dXHARh', '开', 'kāi', 'open', 'actions', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('I42mBtIwEiYc', '开车', 'kāi chē', 'drive; drive a car', 'transportation', 10, NULL, '1-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('QnguspawhLc3', '开会', 'kāi huì', 'have a meeting', 'general', 10, NULL, '1-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('I1P1GqkhzBr1', '开玩笑', 'kāiwánxiào', 'Make fun of', 'actions', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('EwLJgc6tsJTH', '看', 'kàn', 'see', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('qr7ExirFgcTA', '看病', 'kàn bìng', 'see a doctor', 'people', 10, NULL, '4-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('JXesJXryT3X1', '看到', 'kàn dào', 'see', 'actions', 10, NULL, '4-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('hD0sY9KGaz6g', '看见', 'kànjiàn', 'seeing', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('aG30UQCusrf3', '考', 'kǎo', 'test; examine', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('KWD6u0HhvuJX', '考试', 'kǎoshì', 'Examination', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('gMUcacrytM4N', '渴', 'kě', 'thirsty', 'adjectives', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Gs-P1RwPUXeb', '课', 'kè', 'course', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('SPh-_Q_VljoL', '课本', 'kè běn', 'textbook', 'general', 10, NULL, '4-3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('zyXh7UP66H7A', '课文', 'kè wén', 'text', 'general', 10, NULL, '4-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('NI1xY4pB__sI', '口', 'kǒu', 'mouth', 'body', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('AUzxDQ7XsOoM', '块', 'kuài', 'block', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('QeOIlhT-5OA6', '快', 'kuài', 'fast', 'adjectives', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('GS-ApgwcDh_l', '来', 'lái', 'come', 'actions', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('VHQpeNg_6MuJ', '来到', 'lái dào', 'come; arrive', 'actions', 10, NULL, '2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('DhgJxCUEiUZR', '老', 'lǎo', 'old; aged', 'adjectives', 10, 'adjective', '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('4G_lzUvmBfg3', '老人', 'lǎo rén', 'old people; the aged', 'people', 10, NULL, '3-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('zfM2Y_4WXjCX', '老师', 'lǎoshī', 'Teacher', 'people', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('FtKqjNeZsLAf', '了', 'le', 'past tense marker', 'general', 10, NULL, '5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('7EXGlV0XGqp_', '累', 'lèi', 'tired', 'adjectives', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('yXdYhDC0vzFi', '冷', 'lěng', 'cold', 'weather', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('6T4S5EN5ZWCt', '里', 'lǐ', 'in', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('OrNOYOT25uOZ', '里边', 'lǐ biān', 'inside', 'directions', 10, NULL, '3-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Gs0fOrdUvOnM', '两', 'liǎng', 'two', 'numbers', 10, 'number', '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('OL6pFmKtm6cp', '零', 'líng', 'zero', 'numbers', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Jtr3_G-RWWv7', '〇', 'líng', 'zero', 'numbers', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('MAMbwbybELjh', '六', 'liù', 'Six', 'numbers', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Swv62Fr4ZrQ-', '楼', 'lóu', 'floor', 'general', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('6EEWCPDosmWI', '楼上', 'lóu shàng', 'upstairs', 'general', 10, NULL, '2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('kuOnhsC2xFWv', '楼下', 'lóu xià', 'downstairs', 'general', 10, NULL, '2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('XMsK0FfUlSqO', '路', 'lù', 'road', 'transportation', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('dQQlflCNmvnf', '路口', 'lù kǒu', 'intersection; crossing', 'general', 10, NULL, '4-3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('5UF6eN9Gp1gv', '路上', 'lù shàng', 'on the road', 'transportation', 10, NULL, '4-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('iHnvnduf77xI', '妈妈', 'mā ma', 'mom; mother', 'family', 10, NULL, '1-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('5aLr7T5q1ERg', '妈', 'mā', 'mom; mother', 'family', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('T3UO_329f21S', '马路', 'mǎ lù', 'road; street', 'transportation', 10, NULL, '3-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('RsLh4TatEJXx', '马上', 'mǎshàng', 'Right off', 'directions', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('RFVPeNSjkwT7', '吗', 'ma', 'auxiliary word', 'general', 10, NULL, '5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('kzkzlTtuNdvI', '买', 'mǎi', 'buy', 'actions', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('o7l9Xlm2Yq2p', '慢', 'màn', 'slow', 'adjectives', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('u4WvrJNBv1y4', '忙', 'máng', 'busy', 'adjectives', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('IjG_Av7-FGoK', '毛', 'máo', 'a fractional unit of money in China (measure word)', 'objects', 10, 'measure', '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Ow-Q7XrROXvp', '没', 'méi', 'no', 'general', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('n5uy2P2uce7V', '没关系', 'méiguānxi', 'No problem', 'general', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('sMFLccacwIqA', '没什么', 'méi shén me', 'It’s nothing', 'pronouns', 10, NULL, '2-2-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('86lHgqVuJUuI', '没事儿', 'méi shìr', 'It’s okay', 'pronouns', 10, NULL, '2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('7b_fMhz45eNB', '没有', 'méi yǒu', 'have not; no', 'general', 10, NULL, '2-3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('VX0FhQQX5Ht4', '妹妹', 'mèi mei', 'younger sister', 'family', 10, NULL, '4-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('jd4T0hjk32SR', '妹', 'mèi', 'younger sister', 'family', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('KB98Zv4ZajbM', '门', 'mén', 'door', 'objects', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('7pFb1jF8GkU6', '门口', 'mén kǒu', 'doorway', 'general', 10, NULL, '2-3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('zDn8tmPuvuHZ', '门票', 'mén piào', 'tickets', 'general', 10, NULL, '2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Qsz8-SeopQ2z', '们（朋友们）', 'men', 'plural marker for pronouns and a few animate nouns (friends)', 'general', 10, NULL, '5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ftVWNVtyXpil', '米饭', 'mǐfàn', 'Steamed Rice', 'food', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('-v_3bEiKkEFc', '面包', 'miànbāo', 'Bread', 'food', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('iql8u3gGc611', '面条儿', 'miàn tiáor', 'noodles', 'general', 10, NULL, '4-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('KWikwocbX6gu', '名字', 'míngzi', 'Name', 'general', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('QoL7e2fLN09G', '明白', 'míngbai', 'clear', 'general', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('wZ1GJywaY30R', '明年', 'míng nián', 'next year', 'time', 10, NULL, '2-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('3P9Wa43Rx5Gd', '明天', 'míngtiān', 'Tomorrow', 'time', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('N48RUCyRxaoj', '拿', 'ná', 'take', 'actions', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('wHGkVjhpjPZh', '哪', 'nǎ', 'which', 'pronouns', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('3xUcWA62PFZ8', '哪里', 'nǎ lǐ', 'where', 'pronouns', 10, NULL, '3-3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('aCdjkcAzFqtb', '哪儿', 'nǎr', 'where', 'pronouns', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('dNdDRatgzAUT', '哪些', 'nǎ xiē', 'which', 'pronouns', 10, NULL, '3-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('MPg6WtHk_qW7', '那', 'nà', 'that', 'pronouns', 10, 'pronoun', '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('EFCviw_sN-XL', '那边', 'nà biān', 'there', 'general', 10, NULL, '4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('efGbNPqUemBm', '那里', 'nà lǐ', 'there', 'general', 10, NULL, '4-3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('rr4QLd67hbdV', '那儿', 'nàr', 'there', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('R6FT6q5O_3Ta', '那些', 'nà xiē', 'those', 'general', 10, NULL, '4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('GAQd0OUQlmse', '奶', 'nǎi', 'milk', 'food', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('oOnfylzhRjog', '奶奶', 'nǎinai', 'grandma', 'family', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('zK8NBCP9CGpt', '男', 'nán', 'Man', 'people', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('73Q2wig79JGx', '男孩儿', 'nán háir', 'boy', 'people', 10, NULL, '2-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('J1y2t75Rw3xS', '男朋友', 'nán péng yǒu', 'boyfriend', 'general', 10, NULL, '2-2-3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('3mXrzp8ag7GE', '男人', 'nán ren', 'man', 'people', 10, NULL, '2-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Sej6D3kxtZnF', '男生', 'nán shēng', 'boy', 'people', 10, NULL, '2-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('lBkZwUP66Fbz', '南', 'nán', 'south', 'directions', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('JU80lQ1geRGl', '南边', 'nán biān', 'south; south side', 'directions', 10, NULL, '2-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ETRE5F2WCyTi', '难', 'nán', 'hard, difficult', 'adjectives', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('db99rgZ5pKCf', '呢', 'ne', 'auxiliary word', 'general', 10, NULL, '5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('jufIIIJTFWYT', '能', 'néng', 'can', 'general', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('JTkbaTpGLe9q', '你', 'nǐ', 'you', 'pronouns', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('MdD9QDaoMYyA', '你们', 'nǐ men', 'you', 'pronouns', 10, NULL, '3-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('x01Hv6JFE4pX', '年', 'nián', 'year', 'time', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('DXZmFy5fSj6s', '您', 'nín', 'you', 'pronouns', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('t0_dnkzPUKlS', '牛奶', 'niúnǎi', 'milk', 'food', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Pu3Xpwn3CVcg', '女', 'nǚ', 'woman', 'people', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('bzRQEoEyV44C', '女儿', 'nǚ’ér', 'daughter', 'family', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('FKRiOypP9Y6Z', '女孩儿', 'nǚ háir', 'girl', 'people', 10, NULL, '3-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('lMZedR9ySQHW', '女朋友', 'nǚ péng yǒu', 'girlfriend', 'general', 10, NULL, '3-2-3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('DeohT5h4JuSB', '女人', 'nǚ ren', 'woman', 'people', 10, NULL, '3-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('K5anSlGuNwzm', '女生', 'nǚ shēng', 'girl', 'people', 10, NULL, '3-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('omTfIBC6hBvf', '旁边', 'pángbiān', 'Side', 'general', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('wdowXC_sTFKL', '跑', 'pǎo', 'run', 'actions', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('EWnpYZMkMIPb', '朋友', 'péngyou', 'Friend', 'people', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ipB3TthEuFqi', '票', 'piào', 'ticket', 'transportation', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Y4Qmzp2UaEin', '七', 'qī', 'Seven', 'numbers', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('glN4QQH0fttD', '起', 'qǐ', 'get up; start; rise', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('RfYWduloE0vm', '起床', 'qǐchuáng', 'Get up', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ki0k4GWuJFkJ', '起来', 'qǐlái', 'get up', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('WcxcFj3d8zzt', '汽车', 'qì chē', 'car', 'transportation', 10, NULL, '4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('RRfC-IH7y5vD', '前', 'qián', 'front', 'directions', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('MqKdnyykVG6S', '前边', 'qián biān', 'in front', 'directions', 10, NULL, '2-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('T0XmhfjGYeJJ', '前天', 'qián tiān', 'the day before yesterday', 'time', 10, NULL, '2-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('NTR8nyfxojwe', '钱', 'qián', 'money', 'objects', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('d2N2iDreFz-d', '钱包', 'qián bāo', 'wallet', 'general', 10, NULL, '2-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('T3jn9hhHCgTs', '请', 'qǐng', 'please', 'greetings', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('KxVwK5Ldm6Kx', '请假', 'qǐngjià', 'ask for leave', 'actions', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ag3yR61cZOsQ', '请进', 'qǐng jìn', 'please come in', 'actions', 10, NULL, '3-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('4BHWjfO9bcOQ', '请问', 'qǐng wèn', 'excuse me', 'greetings', 10, NULL, '3-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('tdv9V4r8iYQe', '请坐', 'qǐng zuò', 'please have a seat', 'greetings', 10, NULL, '3-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('tZIDKzJ77BXF', '球', 'qiú', 'ball', 'objects', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('PKaxHcLpDxoe', '去', 'qù', 'go', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('KRmIHNFYcm6l', '去年', 'qùnián', 'Last year', 'time', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('JNggs94d9OVh', '热', 'rè', 'heat', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ubd5taE1gAzF', '人', 'rén', 'people', 'people', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('VfSe01KxXiOw', '认识', 'rènshi', 'know', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('38Ujl60M7Pry', '认真', 'rènzhēn', 'earnest', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('I6jnMpwphnCz', '日', 'rì', 'date', 'time', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('CbqXYRRUhVdd', '日期', 'rìqī', 'Date', 'time', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('yXhj6SR5NmBI', '肉', 'ròu', 'meat', 'food', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('OHKRhV2aIX0D', '三', 'sān', 'Three', 'numbers', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Hsbydo8Bn7lR', '山', 'shān', 'mountain', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('vhOlnhLrFFaR', '商场', 'shāng chǎng', 'mall; shopping mall', 'places', 10, NULL, '1-3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('7EMRNeyT05g3', '商店', 'shāngdiàn', 'Shop', 'places', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('vAFjA5Zcvsj-', '上', 'shàng', 'upper', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('HdxmkJOe_rYQ', '上班', 'shàngbān', 'go to work', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ps8foS-TA56C', '上边', 'shàng biān', 'above; on', 'directions', 10, NULL, '4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('QqXYEVIxAD-o', '上车', 'shàng chē', 'get on', 'general', 10, NULL, '4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('3xZCno0XoKvr', '上次', 'shàng cì', 'last time', 'time', 10, NULL, '4-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ODQINKPfFI5K', '上课', 'shàng kè', 'attend class; have a class', 'general', 10, NULL, '4-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('7AeALwHi_3Pz', '上网', 'shàngwǎng', 'Surf the Internet', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('IVzmeIZJWvrx', '上午', 'shàngwǔ', 'morning', 'time', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('85CMPWZCovH_', '上学', 'shàng xué', 'go to school', 'places', 10, NULL, '4-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('bZk63QFQhEKG', '少', 'shǎo', 'less', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('aUMW2yCByRMn', '谁', 'shéi', 'who', 'pronouns', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('5FdZaG0EJI1h', '身上', 'shēn shàng', 'body; on one’s body', 'numbers', 10, NULL, '1-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('pwggAY-B_huN', '身体', 'shēntǐ', 'body', 'body', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ofoOXEOjPKdI', '什么', 'shénme', 'What', 'pronouns', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('XYGoSTTLR7KI', '生病', 'shēngbìng', 'Fall ill', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('y31LZGwcvRvT', '生气', 'shēngqì', 'get angry', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Bk_HPcMpAuYO', '生日', 'shēngrì', 'Birthday', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('0Ys4vPfVqCuX', '十', 'shí', 'Ten', 'numbers', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('feXOSyqAykJX', '时候', 'shíhou', 'time', 'time', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Mv0mlw1gRDl7', '时间', 'shíjiān', 'time', 'time', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('C33zG2babYdc', '事', 'shì', 'thing', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('mQ8f41KfacFC', '试', 'shì', 'try', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('bC1tRVcbq2eM', '是', 'shì', 'yes', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('EwvSqj9zntWY', '是不是', 'shì bú shì', 'isn’t it?', 'pronouns', 10, NULL, '4-2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Z2cFJYNgC7Qb', '手', 'shǒu', 'hand', 'body', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('IcwHtkeHQwgI', '手机', 'shǒujī', 'Mobile phone', 'objects', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('NdUz3WDYnRhF', '书', 'shū', 'book', 'objects', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Otjhd_rsutlh', '书包', 'shū bāo', 'school bag', 'places', 10, NULL, '1-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('cnQBSumCL4Jj', '书店', 'shū diàn', 'bookstore', 'general', 10, NULL, '1-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('eYwaKiv5dxzL', '树', 'shù', 'tree', 'objects', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('fHdX2Hl9Qi-q', '水', 'shuǐ', 'water', 'food', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Bk7OSpz_FxqO', '水果', 'shuǐguǒ', 'Fruits', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('iqPb78kOwlVQ', '睡', 'shuì', 'sleep', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('8HKE4Gt4xJfY', '睡觉', 'shuìjiào', 'sleep', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('JeTfkJhR54gZ', '说', 'shuō', 'speak', 'actions', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('zDcw4QMcW117', '说话', 'shuōhuà', 'talk', 'actions', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('vfUrZ6DAcUqC', '四', 'sì', 'Four', 'numbers', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('8drovjnrsWcw', '送', 'sòng', 'give', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('rDVbHKPRmCtz', '岁', 'suì', 'year, age', 'time', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('wHeTVMrrL03i', '他', 'tā', 'he', 'pronouns', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('qhR0KBEpJEuh', '他们', 'tā men', 'they', 'pronouns', 10, NULL, '1-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('uoLaFe_j2EXi', '她', 'tā', 'she', 'pronouns', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('qLDxaWNmm2hy', '她们', 'tā men', 'they', 'pronouns', 10, NULL, '1-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('dcX5hjKzLo7l', '太', 'tài', 'too', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('jraprOv9Rj8I', '天', 'tiān', 'day', 'time', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Ai1R27WH_eDk', '天气', 'tiānqì', 'weather', 'weather', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('m7CFblld3sLv', '听', 'tīng', 'hear', 'actions', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('aboyQU6IPcFQ', '听到', 'tīng dào', 'hear', 'actions', 10, NULL, '1-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('31oXimjCAq-T', '听见', 'tīng jiàn', 'hear', 'actions', 10, NULL, '1-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('vGtkqJz-oNDq', '听写', 'tīng xiě', 'dictation; dictate', 'general', 10, NULL, '1-3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('o6p0MvBPlpSY', '同学', 'tóngxué', 'Classmate', 'people', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Q7CglHj6Wm-c', '图书馆', 'túshūguǎn', 'Library', 'places', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('FcHzkROrxK7v', '外', 'wài', 'abroad, outside', 'directions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('9JnFqc66jXhG', '外边', 'wài biān', 'outside', 'directions', 10, NULL, '4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('dUm6x0WWB_4x', '外国', 'wài guó', 'foreign country', 'general', 10, NULL, '4-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('i5zPBofzJjX3', '外语', 'wài yǔ', 'foreign language', 'general', 10, NULL, '4-3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('1Jd5V1J7Gur3', '玩儿', 'wánr', 'play', 'actions', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Du-sEqbiiu4P', '晚', 'wǎn', 'late', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('MxUC167E8yUh', '晚饭', 'wǎn fàn', 'dinner', 'food', 10, NULL, '3-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('U-0nVxbN8Y8x', '晚上', 'wǎnshang', 'Night', 'time', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('q0cuCgtAoyN5', '网上', 'wǎng shàng', 'online', 'general', 10, NULL, '3-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('kafdZyrCDJu3', '网友', 'wǎng yǒu', 'net friend', 'people', 10, NULL, '3-3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('PMTru2CNCzSO', '忘', 'wàng', 'forget', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('gnJrqdDhsMjJ', '忘记', 'wàngjì', 'forget', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('8X283hvmqa5m', '问', 'wèn', 'ask', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('mw-uEsRFLu3o', '我', 'wǒ', 'I', 'pronouns', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('H9LI06N6a1UL', '我们', 'wǒmen', 'We', 'pronouns', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('4BimPYKRuSdL', '五', 'wǔ', 'Five', 'numbers', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('HbjNNiTz6CgN', '午饭', 'wǔ fàn', 'lunch', 'food', 10, NULL, '3-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('gkoAiYH1j6va', '西', 'xī', 'west', 'directions', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('cefPX_1CO4pJ', '西边', 'xī biān', 'west; west side', 'directions', 10, NULL, '1-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('i6Vmyb5KeML7', '洗', 'xǐ', 'wash', 'actions', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('fka3pwWqJL3o', '洗手间', 'xǐshǒujiān', 'Restroom', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('DmjC4yuHcY1S', '喜欢', 'xǐhuan', 'like', 'actions', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('PEyuzhj60DAJ', '下（名、动）', 'xià', 'below; under; next; go down; get off', 'directions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('vnGKiHCNp5We', '下班', 'xià bān', 'get off work', 'general', 10, NULL, '4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('QCeGD_UtRJ5E', '下边', 'xià biān', 'below; under', 'directions', 10, NULL, '4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('3-lvfuHs2hnN', '下车', 'xià chē', 'get off', 'general', 10, NULL, '4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('nA4oD0H8fvEV', '下次', 'xià cì', 'next time', 'time', 10, NULL, '4-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('nuJ0AafnEJw2', '下课', 'xià kè', 'finish class', 'general', 10, NULL, '4-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('f_6t3-jvgeIh', '下午', 'xiàwǔ', 'Afternoon', 'time', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('2AEh1L_XFtMH', '下雨', 'xiàyǔ', 'rain', 'weather', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('E59FXuwUODAi', '先', 'xiān', 'before', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('jAkvS9TktiZr', '先生', 'xiānsheng', 'Sir', 'people', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('lOyYdbh-DbSQ', '现在', 'xiànzài', 'Now', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('EakMCNLj8agu', '想', 'xiǎng', 'think', 'actions', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('VBQhmTkN4Yra', '小', 'xiǎo', 'Small', 'adjectives', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('SzTIXk2uwvO2', '小孩儿', 'xiǎo háir', 'child; kid', 'family', 10, NULL, '3-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('n7M3pASdPcru', '小姐', 'xiǎojiě', 'Miss', 'people', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Za9s5uXGtsQz', '小朋友', 'xiǎo péng yǒu', 'child; kid', 'family', 10, NULL, '3-2-3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('WB__8oQBPht_', '小时', 'xiǎoshí', 'hour', 'time', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('vVbcFcE_yFrv', '小学', 'xiǎo xué', 'primary school; elementary school', 'places', 10, NULL, '3-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ohQ8eg2GV_Az', '小学生', 'xiǎo xué shēng', 'elementary school student', 'places', 10, NULL, '3-2-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('JijF-lFI8eeE', '笑', 'xiào', 'laugh', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('fKNRaOoPmVXn', '写', 'xiě', 'write', 'actions', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('qzXayv-AvNMq', '谢谢', 'xièxie', 'Thank you', 'pronouns', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Yq4rxDVa1Saw', '新', 'xīn', 'new', 'adjectives', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('m-oy8YaGimC_', '新年', 'xīn nián', 'New Year', 'time', 10, NULL, '1-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('lGIHnC8Ac92X', '星期', 'xīngqī', 'week', 'time', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('fxLMx-q9fDnN', '星期日', 'xīng qī rì', 'Sunday', 'general', 10, NULL, '1-1-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('k3kKC_4AtrKy', '星期天', 'xīng qī tiān', 'Sunday', 'general', 10, NULL, '1-1-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('7bI_oHEtQGQG', '行', 'xíng', 'That’s ok', 'pronouns', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('xCIdTkGa5hld', '休息', 'xiūxi', 'Rest', 'actions', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('zF7eho6amg7T', '学', 'xué', 'learn; study', 'actions', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('03ddpU4jrRo5', '学生', 'xuésheng', 'Student', 'people', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('lxWYxeo-mxkA', '学习', 'xuéxí', 'Study', 'actions', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Sq4ruHZ7GctU', '学校', 'xuéxiào', 'School', 'places', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('dVZPKuVGWOcO', '学院', 'xué yuàn', 'college; academy', 'general', 10, NULL, '2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ean5LdCyl54W', '要', 'yào', 'want', 'actions', 10, 'verb', '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('1uNcOVNlTICL', '爷爷', 'yéye', 'grandpa', 'family', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('1D2obAkgbqqP', '也', 'yě', 'also', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('BCP55kt7s3-X', '页', 'yè', 'page', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('hyvB8LCn2LFO', '一', 'yī', 'One', 'numbers', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('DXy6gChVbVmO', '衣服', 'yīfu', 'clothes', 'objects', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('mwuNN5cFlq7o', '医生', 'yīshēng', 'Doctor', 'people', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('FFZX2m41Zkyl', '医院', 'yīyuàn', 'Hospital', 'places', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('3Xi252JjFtZh', '一半', 'yí bàn', 'half', 'numbers', 10, NULL, '2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('eITQLTAbtQ0N', '一会儿', 'yíhuìr', 'A little while', 'general', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('wEasaDp5KBbA', '一块儿', 'yí kuàir', 'together', 'general', 10, NULL, '2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('1sSzYq0CqfQP', '一下儿', 'yí xiàr', 'a little bit', 'general', 10, NULL, '2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('3pZGcSg2zWvd', '一样', 'yíyàng', 'equally', 'general', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('5ldXmckYxo4-', '一边', 'yìbiān', 'One side', 'numbers', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ODmI-zegm6ko', '一点儿', 'yīdiǎnr', 'a little bit', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('8ZKXr7rq1Bra', '一起', 'yìqǐ', 'together', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('EpoRwQAJ7aCP', '一些', 'yì xiē', 'some', 'general', 10, NULL, '4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('wyn9WZVBEdmH', '用', 'yòng', 'use', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('BqoG8tvRa5Es', '有', 'yǒu', 'have', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Z3PpvTOuHVER', '有的', 'yǒu de', 'some', 'general', 10, NULL, '3-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('_5YDN_MeiHNb', '有名', 'yǒumíng', 'Famous', 'adjectives', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('r-2GbhZcY-6G', '有时候', 'yǒu shí hòu', 'sometimes', 'general', 10, NULL, '3-2-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('2TkeAsOt_n99', '有时', 'yǒu shí', 'sometimes', 'general', 10, NULL, '3-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('RRTpLmpC6RL5', '有（一）些', 'yǒu  xiē', 'some', 'general', 10, NULL, '3-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Lq2nzBFPodcG', '有用', 'yǒu yòng', 'useful', 'general', 10, NULL, '3-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('9x9yx9mQiLx9', '右', 'yòu', 'right', 'directions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('KXa_n6MU6wCe', '右边', 'yòubian', 'Right', 'directions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('RyXUO1VbqTjy', '雨', 'yǔ', 'rain', 'weather', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('bkHK21SlikIo', '元', 'yuán', 'element; Yuan', 'general', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('5hXi-HHjAVNt', '远', 'yuǎn', 'far', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('hCqXMh1SAXU6', '月', 'yuè', 'month', 'time', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('dyzx7WFPhjN_', '再', 'zài', 'again', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('jLwUoi2PLJ50', '再见', 'zàijiàn', 'Bye', 'greetings', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('5LR2zzs0yUat', '在', 'zài', 'stay; in process of', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ME00tK7uIznw', '在家', 'zài jiā', 'at home', 'places', 10, NULL, '4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('wSn87fuLthoj', '早', 'zǎo', 'early', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('rsE7druAQIvG', '早饭', 'zǎo fàn', 'breakfast', 'food', 10, NULL, '3-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('YfjqaDu4pCYV', '早上', 'zǎoshang', 'Morning', 'time', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('BoDPyp8arU9B', '怎么', 'zěnme', 'How', 'pronouns', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('uS3dGO65ap38', '站', 'zhàn', 'station', 'places', 10, 'noun', '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('wvwb_FKAYXlQ', '找', 'zhǎo', 'look for', 'actions', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ZK3UD1nz0QxZ', '找到', 'zhǎo dào', 'find', 'general', 10, NULL, '3-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('zLqD23z8rAuN', '这', 'zhè', 'Here (here)', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('y4wowFtvLqwY', '这边', 'zhè biān', 'here', 'general', 10, NULL, '4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('i28FecYxzc2D', '这里', 'zhè lǐ', 'here', 'general', 10, NULL, '4-3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('sgF_l6jqycBZ', '这儿', 'zhèr', 'here', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Hbp9Si_SoN-a', '这些', 'zhè xiē', 'these', 'general', 10, NULL, '4-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('4BZbq_hxqftp', '着', 'zhe', 'in process of', 'general', 10, NULL, '5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('e_G3guKAkD2C', '真', 'zhēn', 'really', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('PUmO7CsyiPeb', '真的', 'zhēn de', 'really', 'general', 10, NULL, '1-5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('LJytE1msvzlM', '正', 'zhèng', 'just; exactly', 'general', 10, 'adverb', '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('83UzcJlGUEeK', '正在', 'zhèngzài', 'in process of', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('E5L2dRSwxyyj', '知道', 'zhīdào', 'know', 'actions', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('AW5sqFGIuDBS', '知识', 'zhīshi', 'knowledge', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('bI6fZzZoYAN2', '中', 'zhōng', 'middle; in', 'directions', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('IpQePI_xFWbL', '中国', 'zhōngguó', 'China', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('nrEHuFU9HiIw', '中间', 'zhōngjiān', 'Middle', 'directions', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('3yson3iorhv4', '中文', 'zhōngwén', 'Chinese', 'general', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('u5e43ukv1bSQ', '中午', 'zhōngwǔ', 'Noon', 'time', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('b3YlGClxXUpj', '中学', 'zhōng xué', 'middle school', 'places', 10, NULL, '1-2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('9Fz4_CKWKEcW', '中学生', 'zhōng xué shēng', 'middle School student', 'places', 10, NULL, '1-2-1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('m95Fs9ePOOgV', '重', 'zhòng', 'heavy', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ID-9lJOrN2J0', '重要', 'zhòngyào', 'important', 'adjectives', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('6HvJqLaD-r8-', '住', 'zhù', 'live', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('jAB10iWBC2FN', '准备', 'zhǔnbèi', 'Get ready', 'general', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('qAPILPo45RC0', '桌子', 'zhuōzi', 'Table', 'objects', 10, NULL, '1');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('RTzPwRoaymzS', '字', 'zì', 'word, character', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('QUz07ud74qXZ', '子（桌子）', 'zi', 'noun suffix (table)', 'objects', 10, NULL, '5');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('hB6gOUAIIrFl', '走', 'zǒu', 'go, walk', 'transportation', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('txAsQ_MMtaHp', '走路', 'zǒu lù', 'walk', 'transportation', 10, NULL, '3-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('bx1X9P36j1p6', '最', 'zuì', 'most', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('grhv7nQwIY_9', '最好', 'zuìhǎo', 'Best', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('-SfS1Knc-fB3', '最后', 'zuìhòu', 'Last', 'general', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('tZ5TPbVYAQjF', '昨天', 'zuótiān', 'Yesterday', 'time', 10, NULL, '2');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('7rEsF0TJp4xW', '左', 'zuǒ', 'left', 'directions', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('ct22B2BIJxJC', '左边', 'zuǒbian', 'left', 'directions', 10, NULL, '3');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('FYcSKiHP9Bre', '坐', 'zuò', 'sit', 'actions', 10, NULL, '4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('IEw_OGE-JvS6', '坐下', 'zuò xià', 'sit down', 'actions', 10, NULL, '4-4');
INSERT INTO vocabulary (id, hanzi, pinyin, english, category, hsk_level, pos, tone_pattern) VALUES ('Pp3LdF-b081I', '做', 'zuò', 'do', 'actions', 10, NULL, '4');

-- Done! Now go to Vocab Manager and select "HSK 1 (v3.0)" to see the new words.
-- Compare with "HSK 1 (Old)" to verify everything looks correct.